# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09f9979ed1bf66361ac3ba6c0fad4b9786a75ed2fc566ce03962905fb4d7c8fff4c221dc250bd11dd11f648e75acfbd238d6f1db9c78863e2496581dbfa69f0e

test:
  secret_key_base: 400c5cc9659e035118ed916a0016edfcdc5011da0ad259dac7c528bc85cc56b381d3bc81dd980d908ad7ce9f9796125c180c2f215e41e2152494a48bd9f1fa96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
